name: Auto Fetch Sky APK Link

on:
  schedule:
    - cron: '0 4 * * *' # UTC 04:00 / GMT+8 12:00
  workflow_dispatch: # 允許手動觸發

jobs:
  update-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write # 確保有權限推送到 Repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python Script
        env:
          PYTHON: ${{ secrets.PYTHON }}
          API_URL: ${{ secrets.API_URL }}
          PKG_NAMES_ENV: ${{ secrets.PKG_NAMES_ENV }}
        run: python $PYTHON_SCRIPT

      - name: Commit and Push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add history.json

          git commit -m "Auto-update download link history" || echo "No changes to commit"

          git push
